# Generated by Django 4.2 on 2023-07-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredUser',
            new_name='User',
        ),
    ]
