# Generated by Django 4.2 on 2023-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_user_email_user_firstname_user_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
