# Generated by Django 4.2 on 2023-07-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_user_password_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(default='', max_length=50)),
                ('jobDescription', models.CharField(default='', max_length=1000)),
                ('jobRequirement', models.CharField(default='', max_length=1000)),
                ('companyName', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
