# Generated by Django 4.2 on 2023-08-05 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0010_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
